<!DOCTYPE html>
<html>
<head>
	<title>La Manuela</title>
	<link rel="stylesheet" type="text/css" href="css/estilo.css">
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/utilidades.js"></script>
</head>
<body>
	<div id="principal">
		<header>
			<div class="FI" id="logo">

			</div>
			<div class="FD" id="login">
			
			</div>
		</header>
		<?php
			include_once('menu.inc');
		?>
		<div id="contenido">

